name: CI
on:
  push:
    braches:
      - release
      - develop
jobs:
  build:
  name: "Build apk and ios"
  runs_on : macos-latest
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
      channel: 'stable' # or: 'beta', 'dev' or 'master'
    - run: flutter pub get
    - run: flutter build apk
    - uses: ncipollo/release-actions@v1
      with:
        articrafts: "build/app/outputs/apk/release/*.apk"
        tag: v1.0.${{ github.run_number }}
        token: ${{ secrets.TOKEN }}